### Numpy
- 데이터는 행열로 표현
- 행열 데이터 빠르게 계산을 해야 합니다.
- 행열 데이터 생성, 수정, 계산 등을 빠르게 처리해주는 패키지
- 특징
    - C, C++, 포트란으로 작성
    - 선형대수학을 빠르게 연산
        - 스칼라, 벡터, 매트릭스

In [2]:
import numpy as np

In [3]:
# 행렬 데이터 생성
# ndarray : 한가지 데이터 타입만 값으로 사용이 가능

In [4]:
array = np.array([1, 2, 3]) # 객체로 만들어서 연산해주어야 함, 클래스 개념
type(array), array # __str__

(numpy.ndarray, array([1, 2, 3]))

In [8]:
array2 = np.array(
    [[1, 2, 3],
    [4, 5, 6]]
)
array2, array2.ndim, array2.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [10]:
# 행렬의 모양(shape) 변경하기
array2.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
# 행렬 데이터의 선택 : offset index : masking

In [12]:
array2[1][::-1]

array([6, 5, 4])

In [13]:
array2[1, 2] # array2[1][2]

6

In [14]:
# 데이터 수정

In [15]:
ls = [1,2,3]
ls[1] = 5
ls

[1, 5, 3]

In [17]:
array2[1][2] = 10
array2

array([[ 1,  2,  3],
       [ 4,  5, 10]])

In [20]:
# 브로드 캐스팅
array2[0] = 0
array2

array([[ 0,  0,  0],
       [ 4,  5, 10]])

In [21]:
array2[0] = [7, 8, 9]
array2

array([[ 7,  8,  9],
       [ 4,  5, 10]])

In [23]:
# 조건으로 선택
idx = array2 > 7
idx

array([[False,  True,  True],
       [False, False,  True]])

In [24]:
array2[idx]

array([ 8,  9, 10])

In [26]:
array2[idx] = 100
array2

array([[  7, 100, 100],
       [  4,   5, 100]])

In [27]:
# 행렬 데이터의 생성 2

In [28]:
data = np.zeros((2, 3))
data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
data.dtype

dtype('float64')

In [30]:
data2 = data.astype("int")
data2.dtype

dtype('int32')

In [31]:
data = np.ones((2, 3, 2))
data

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [32]:
# arange
np.arange(5)

array([0, 1, 2, 3, 4])

In [33]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [34]:
np.arange(5, 10, 2)

array([5, 7, 9])